import { 
  PenTool, FileText, Image as ImageIcon, Terminal, Share2, 
  Mic, FileUser, Search, Palette, Calculator 
} from 'lucide-react';

export const TOOLS = [
  { 
    id: 'write', 
    slug: 'nional-write',
    name: 'Nional Write', 
    desc: 'AI Copywriting & Paraphrasing', 
    longDesc: 'Transform your writing with the power of AI. Nional Write isn\'t just a spellchecker—it\'s your creative partner. Generate compelling blog posts, emails, and social media captions in seconds, or rewrite existing content to match any tone you need.',
    icon: PenTool, 
    color: 'from-orange-400 to-red-500', 
    bg: 'bg-orange-50 dark:bg-orange-950/30',
    text: 'text-orange-600 dark:text-orange-400',
    status: 'Active',
    href: '/write',
    features: [
        { title: 'Smart Paraphrasing', desc: 'Reword text to be more professional, creative, or concise instantly.' },
        { title: 'Tone Adjustment', desc: 'Switch between Friendly, Academic, Persuasive, and more.' },
        { title: 'Grammar Polish', desc: 'Fix errors and improve flow automatically.' },
        { title: 'Mobile Ready', desc: 'Write on the go with a fully responsive interface.' }
    ],
    faq: [
        { q: 'Is Nional Write free?', a: 'Yes, it is completely free to use for all standard features.' },
        { q: 'Do you store my texts?', a: 'No, we prioritize privacy. Your texts are processed but not stored.' }
    ]
  },
  { 
    id: 'pdf', 
    slug: 'student-scanner',
    name: 'Student Scanner', 
    desc: 'Chat with PDF & Summarize', 
    longDesc: 'Study smarter, not harder. Upload any PDF—textbooks, research papers, or contracts—and chat with it. Ask questions, get summaries, and find exactly what you need without reading hundreds of pages.',
    icon: FileText, 
    color: 'from-blue-400 to-indigo-500', 
    bg: 'bg-blue-50 dark:bg-blue-950/30',
    text: 'text-blue-600 dark:text-blue-400',
    status: 'Coming Soon',
    href: '#',
    features: [
        { title: 'Instant Summaries', desc: 'Get the gist of long documents in seconds.' },
        { title: 'Q&A Chat', desc: 'Ask specific questions about the content.' },
        { title: 'Citation Finder', desc: 'Locate exactly where the information comes from.' }
    ],
    faq: []
  },
  { 
    id: 'img', 
    slug: 'image-magic',
    name: 'Image Magic', 
    desc: 'Remove BG & Upscale', 
    longDesc: 'Professional image editing tools right in your browser. Remove backgrounds, upscale low-res photos, and optimize images for the web with a single click.',
    icon: ImageIcon, 
    color: 'from-purple-400 to-pink-500', 
    bg: 'bg-purple-50 dark:bg-purple-950/30',
    text: 'text-purple-600 dark:text-purple-400',
    status: 'Coming Soon',
    href: '#',
    features: [],
    faq: []
  },
  { 
    id: 'dev', 
    slug: 'dev-toolbox',
    name: 'Dev Toolbox', 
    desc: 'JSON, Regex & Formatters', 
    longDesc: 'Essential utilities for developers. Format JSON, test Regex patterns, convert timestamps, and more—all in one clean, ad-free dashboard.',
    icon: Terminal, 
    color: 'from-green-400 to-emerald-500', 
    bg: 'bg-green-50 dark:bg-green-950/30',
    text: 'text-green-600 dark:text-green-400',
    status: 'Coming Soon',
    href: '#',
    features: [],
    faq: []
  },
  { 
    id: 'social', 
    slug: 'viral-hooks',
    name: 'Viral Hooks', 
    desc: 'Social Media Generator', 
    longDesc: 'Crack the algorithm with AI-generated hooks for TikTok, Twitter/X, and Instagram. Input your topic, and get engaging opening lines that stop the scroll.',
    icon: Share2, 
    color: 'from-pink-400 to-rose-500', 
    bg: 'bg-pink-50 dark:bg-pink-950/30',
    text: 'text-pink-600 dark:text-pink-400',
    status: 'Coming Soon',
    href: '#',
    features: [],
    faq: []
  },
  { 
    id: 'audio', 
    slug: 'audio-scribe',
    name: 'Audio Scribe', 
    desc: 'AI Speech to Text', 
    longDesc: 'Convert interviews, lectures, and voice notes into accurate text. Supports multiple languages and speaker detection.',
    icon: Mic, 
    color: 'from-red-400 to-orange-500', 
    bg: 'bg-red-50 dark:bg-red-950/30',
    text: 'text-red-600 dark:text-red-400',
    status: 'Coming Soon',
    href: '#',
    features: [],
    faq: []
  },
  { 
    id: 'resume', 
    slug: 'resume-ai',
    name: 'Resume AI', 
    desc: 'Smart Resume Builder', 
    longDesc: 'Build a resume that beats the ATS. Input your experience and let AI format it into a professional, keyword-optimized CV.',
    icon: FileUser, 
    color: 'from-cyan-400 to-blue-500', 
    bg: 'bg-cyan-50 dark:bg-cyan-950/30',
    text: 'text-cyan-600 dark:text-cyan-400',
    status: 'Coming Soon',
    href: '#',
    features: [],
    faq: []
  },
  { 
    id: 'seo', 
    slug: 'seo-audit',
    name: 'SEO Audit', 
    desc: 'Website Analyzer', 
    longDesc: 'Get actionable insights to improve your search ranking. Scan your site for technical issues, speed problems, and keyword opportunities.',
    icon: Search, 
    color: 'from-yellow-400 to-amber-500', 
    bg: 'bg-yellow-50 dark:bg-yellow-950/30',
    text: 'text-yellow-600 dark:text-yellow-400',
    status: 'Coming Soon',
    href: '#',
    features: [],
    faq: []
  },
  { 
    id: 'palette', 
    slug: 'palette-gen',
    name: 'Palette Gen', 
    desc: 'AI Color Schemes', 
    longDesc: 'Generate perfect color palettes for your next project. Based on color theory and trending design aesthetics.',
    icon: Palette, 
    color: 'from-indigo-400 to-purple-500', 
    bg: 'bg-indigo-50 dark:bg-indigo-950/30',
    text: 'text-indigo-600 dark:text-indigo-400',
    status: 'Coming Soon',
    href: '#',
    features: [],
    faq: []
  },
  { 
    id: 'math', 
    slug: 'math-genius',
    name: 'Math Genius', 
    desc: 'Step-by-step Solver', 
    longDesc: 'Stuck on a problem? Snap a photo or type it in. Math Genius solves algebra, calculus, and statistics problems with step-by-step explanations.',
    icon: Calculator, 
    color: 'from-teal-400 to-green-500', 
    bg: 'bg-teal-50 dark:bg-teal-950/30',
    text: 'text-teal-600 dark:text-teal-400',
    status: 'Coming Soon',
    href: '#',
    features: [],
    faq: []
  },
];
